language: 'ko-KR'
early_access: false
reviews:
  profile: 'chill'
  request_changes_workflow: false
  high_level_summary: false
  high_level_summary_in_walkthrough: false
  poem: false
  review_status: false
  collapse_walkthrough: false
  auto_review:
    enabled: true
    drafts: false
    auto_incremental_review: false
chat:
  auto_review:
    enabled: false
    drafts: false
finishing_touches:
  docstrings:
    enabled: false
  unit_tests:
    enabled: false
